language: objective-c
install:
- gem install xcpretty
script:
- set -o pipefail && xcodebuild -project "Dispatch.xcodeproj" -scheme "Dispatch" build analyze test | xcpretty
notifications:
    slack: xs-labs:FXh1yLXNkpcVxKZhZU6icdhI
